<?php

namespace Vispanlab\UserBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Vispanlab\UserBundle\Wantlet\ORM\Point;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Vispanlab\CommonBundle\Entity\Repositories\BaseRepository
{
}
