imports:
    - { resource: '@VispanlabAdminBundle/Resources/config/sonata.yml' }

services:
    security.acl.voter.admin_permissions:
        class: Vispanlab\AdminBundle\Voter\AdminAclVoter
        public: false
        arguments:
            - "@security.acl.provider"
            - "@security.acl.object_identity_retrieval_strategy"
            - "@security.acl.security_identity_retrieval_strategy"
            - "@security.acl.permission.map"
            - "@?logger"
        tags:
            - { name: monolog.logger, channel: security }
            - { name: security.voter, priority: 255 }
    area_of_expertise.admin:
        class: Vispanlab\AdminBundle\Admin\AreaOfExpertiseAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Βιβλιοθήκη Εννοιών, label: Γνωστικά Αντικείμενα }
        arguments: [null, Vispanlab\SiteBundle\Entity\AreaOfExpertise, SonataAdminBundle:CRUD]
        calls:
            - [ addChild, ["@concept.admin"] ]
    concept.admin:
        class: Vispanlab\AdminBundle\Admin\ConceptAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Βιβλιοθήκη Εννοιών, label: Έννοιες }
        arguments: [null, Vispanlab\SiteBundle\Entity\Concept, SonataAdminBundle:CRUD]
        calls:
            - [ setSecurityContext, ["@security.context"] ]
    definition.admin:
        class: Vispanlab\AdminBundle\Admin\DefinitionAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, group: Definitions, label: Definitions }
        arguments: [null, Vispanlab\SiteBundle\Entity\Definition, SonataAdminBundle:CRUD]
    user.admin:
        class: Vispanlab\AdminBundle\Admin\UserAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Διαχείριση Χρηστών, label: Χρήστες }
        arguments: [null, Vispanlab\UserBundle\Entity\User, SonataAdminBundle:CRUD]
    subjectarea.admin:
        class: Vispanlab\AdminBundle\Admin\SubjectAreaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Εικονικές Ασκήσεις, label: Θεματικές Ενότητες }
        arguments: [null, Vispanlab\SiteBundle\Entity\SubjectArea, SonataAdminBundle:CRUD]
        calls:
            - [ setSecurityContext, ["@security.context"] ]
    # Exercises
    multiplechoice.admin:
        class: Vispanlab\AdminBundle\Admin\Exercise\MultipleChoiceAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Εικονικές Ασκήσεις, label: Πολλαπλής Επιλογής }
        arguments: [null, Vispanlab\SiteBundle\Entity\Exercise\MultipleChoice, SonataAdminBundle:CRUD]
        calls:
            - [ setSecurityContext, ["@security.context"] ]
    onoff.admin:
        class: Vispanlab\AdminBundle\Admin\Exercise\OnOffAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Εικονικές Ασκήσεις, label: Σωστό/Λάθος }
        arguments: [null, Vispanlab\SiteBundle\Entity\Exercise\OnOff, SonataAdminBundle:CRUD]
    solved.admin:
        class: Vispanlab\AdminBundle\Admin\Exercise\SolvedAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Εικονικές Ασκήσεις, label: Λυμένες }
        arguments: [null, Vispanlab\SiteBundle\Entity\Exercise\Solved, SonataAdminBundle:CRUD]
        calls:
            - [ setSecurityContext, ["@security.context"] ]
    matching.admin:
        class: Vispanlab\AdminBundle\Admin\Exercise\MatchingAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Εικονικές Ασκήσεις, label: Αντιστοίχισης }
        arguments: [null, Vispanlab\SiteBundle\Entity\Exercise\Matching, SonataAdminBundle:CRUD]
        calls:
            - [ setSecurityContext, ["@security.context"] ]
    # Disable gallery
    sonata.media.admin.gallery:
        class: %sonata.media.admin.gallery.class%
        tags:
            - { name: sonata.admin, manager_type: orm, show_in_dashboard: false, label_catalogue: %sonata.media.admin.media.translation_domain% , label_translator_strategy: sonata.admin.label.strategy.underscore }
        arguments:
            - ~
            - %sonata.media.admin.gallery.entity%
            - %sonata.media.admin.gallery.controller%
            - "@sonata.media.pool"
        calls:
            - [setTranslationDomain, [%sonata.media.admin.media.translation_domain%]]
            - [setTemplates, [{ list: SonataMediaBundle:GalleryAdmin:list.html.twig }]]