services:
    tei.securiy.validator.unique:
        class: Vispanlab\UserBundle\Security\Constraints\UniqueEntityInTEIValidator
        arguments: ["@tei_user_provider"]
        tags:
            - { name: validator.constraint_validator, alias: tei_unique }
    tei.security.authentication.provider:
        class: Vispanlab\UserBundle\Security\Authentication\Provider\TEIProvider
        arguments: ["@security.user_checker", "", "@tei_user_provider", true]
    tei_user_provider:
        class: Vispanlab\UserBundle\Security\TEIUserProvider
        arguments: ["@fos_user.user_manager"]
    vispanlab.registration_listener:
        class: Vispanlab\UserBundle\Extension\RegistrationListener
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: kernel.event_subscriber }