<?php

namespace Vilaspa\UserBundle\Entity\Repositories;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Vilaspa\UserBundle\Wantlet\ORM\Point;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Vilaspa\CommonBundle\Entity\Repositories\BaseRepository
{
}
